// /features/templates/data.ts

import { Templates } from "@prisma/client";

export interface TemplateOption {
  id: Templates;
  name: string;
  description: string;
  icon: string;
  color: string;
  popularity: number;
  tags: string[];
  features: string[];
  category: "Frontend" | "Backend" | "FullStack" | "Language";
}

export const templates: TemplateOption[] = [
  // Frontend
  {
    id: Templates.REACTJS,
    name: "React",
    description: "A JavaScript library for building UI",
    icon: "/react.svg",
    color: "#61DAFB",
    popularity: 5,
    tags: ["Frontend"],
    features: ["Components", "JSX", "Virtual DOM"],
    category: "Frontend",
  },
  {
    id: Templates.REACT_VITE,
    name: "React (Vite)",
    description: "React with Vite for fast builds",
    icon: "/vite.svg",
    color: "#646CFF",
    popularity: 5,
    tags: ["Frontend", "Vite"],
    features: ["Fast HMR", "ESM", "Optimized Build"],
    category: "Frontend",
  },
  {
    id: Templates.NEXTJS,
    name: "Next.js",
    description: "FullStack React framework",
    icon: "/nextjs-icon.svg",
    color: "#000000",
    popularity: 5,
    tags: ["FullStack", "React"],
    features: ["SSR", "App Router", "API Routes"],
    category: "FullStack",
  },
  {
    id: Templates.VUE_VITE,
    name: "Vue (Vite)",
    description: "Vue with Vite setup",
    icon: "/vuejs-icon.svg",
    color: "#4FC08D",
    popularity: 4,
    tags: ["Frontend"],
    features: ["Reactivity", "Composition API"],
    category: "Frontend",
  },
  {
    id: Templates.NUXT,
    name: "Nuxt",
    description: "Vue FullStack framework",
    icon: "/nuxt.svg",
    color: "#00DC82",
    popularity: 4,
    tags: ["FullStack", "Vue"],
    features: ["SSR", "Modules", "Routing"],
    category: "FullStack",
  },
  {
    id: Templates.ANGULAR,
    name: "Angular",
    description: "Enterprise Frontend framework",
    icon: "/angular.svg",
    color: "#DD0031",
    popularity: 4,
    tags: ["Frontend"],
    features: ["DI", "RxJS", "CLI"],
    category: "Frontend",
  },
  {
    id: Templates.SVELTE,
    name: "Svelte",
    description: "Compiler-based Frontend framework",
    icon: "/svelte.svg",
    color: "#FF3E00",
    popularity: 4,
    tags: ["Frontend"],
    features: ["No Virtual DOM", "Reactive"],
    category: "Frontend",
  },
  {
    id: Templates.ASTRO,
    name: "Astro",
    description: "Modern static site builder",
    icon: "/astro.svg",
    color: "#FF5D01",
    popularity: 3,
    tags: ["Frontend"],
    features: ["Islands", "Zero JS", "Markdown"],
    category: "Frontend",
  },

  // Backend
  {
    id: Templates.NODE_EXPRESS,
    name: "Node + Express",
    description: "Minimal Node.js Backend",
    icon: "/express.svg",
    color: "#000000",
    popularity: 5,
    tags: ["Backend"],
    features: ["Routing", "Middleware"],
    category: "Backend",
  },
  {
    id: Templates.NODE_FASTIFY,
    name: "Node + Fastify",
    description: "Fast Backend framework",
    icon: "/fastify.svg",
    color: "#000000",
    popularity: 4,
    tags: ["Backend"],
    features: ["High Performance", "Schema Validation"],
    category: "Backend",
  },
  {
    id: Templates.NODE_HONO,
    name: "Hono",
    description: "Lightweight edge Backend",
    icon: "/hono.svg",
    color: "#E36002",
    popularity: 4,
    tags: ["Backend"],
    features: ["Edge Runtime", "Lightweight"],
    category: "Backend",
  },
  {
    id: Templates.NODE_NEST,
    name: "NestJS",
    description: "Scalable Node framework",
    icon: "/nestjs.svg",
    color: "#E0234E",
    popularity: 5,
    tags: ["Backend"],
    features: ["Modular", "DI", "TypeScript"],
    category: "Backend",
  },

  // FullStack
  {
    id: Templates.MERN,
    name: "MERN Stack",
    description: "MongoDB + Express + React + Node",
    icon: "/mern.svg",
    color: "#3FA037",
    popularity: 5,
    tags: ["FullStack"],
    features: ["REST APIs", "SPA"],
    category: "FullStack",
  },
  {
    id: Templates.MEAN,
    name: "MEAN Stack",
    description: "MongoDB + Express + Angular + Node",
    icon: "/mean.svg",
    color: "#DD0031",
    popularity: 4,
    tags: ["FullStack"],
    features: ["MVC", "TypeScript"],
    category: "FullStack",
  },
  {
    id: Templates.T3_STACK,
    name: "T3 Stack",
    description: "Next.js + tRPC + Prisma",
    icon: "/t3.svg",
    color: "#000000",
    popularity: 5,
    tags: ["FullStack"],
    features: ["End-to-End Types", "tRPC"],
    category: "FullStack",
  },
  {
    id: Templates.NEXT_PRISMA,
    name: "Next.js + Prisma",
    description: "Next.js with Prisma ORM",
    icon: "/prisma.svg",
    color: "#000000",
    popularity: 5,
    tags: ["FullStack"],
    features: ["ORM", "SSR"],
    category: "FullStack",
  },

  // LanguageS
  {
    id: Templates.PYTHON,
    name: "Python",
    description: "General-purpose Language",
    icon: "/python.svg",
    color: "#3776AB",
    popularity: 5,
    tags: ["Language"],
    features: ["Simple Syntax", "Libraries"],
    category: "Language",
  },
  {
    id: Templates.JAVA,
    name: "Java",
    description: "Enterprise Backend Language",
    icon: "/java.svg",
    color: "#007396",
    popularity: 5,
    tags: ["Language"],
    features: ["JVM", "Scalable"],
    category: "Language",
  },
  {
    id: Templates.GO,
    name: "Go",
    description: "Fast compiled Backend Language",
    icon: "/go.svg",
    color: "#00ADD8",
    popularity: 4,
    tags: ["Language"],
    features: ["Concurrency", "Fast"],
    category: "Language",
  },
  {
    id: Templates.RUST,
    name: "Rust",
    description: "Memory-safe systems Language",
    icon: "/rust.svg",
    color: "#000000",
    popularity: 4,
    tags: ["Language"],
    features: ["Memory Safety", "Performance"],
    category: "Language",
  },
  {
    id: Templates.CPP,
    name: "C++",
    description: "High-performance Language",
    icon: "/cpp.svg",
    color: "#00599C",
    popularity: 4,
    tags: ["Language"],
    features: ["OOP", "Performance"],
    category: "Language",
  },
  {
    id: Templates.C,
    name: "C",
    description: "Low-level programming",
    icon: "/c.svg",
    color: "#A8B9CC",
    popularity: 4,
    tags: ["Language"],
    features: ["Pointers", "Low-level"],
    category: "Language",
  },
  {
    id: Templates.CSHARP,
    name: "C#",
    description: ".NET programming Language",
    icon: "/csharp.svg",
    color: "#512BD4",
    popularity: 4,
    tags: ["Language"],
    features: [".NET", "OOP"],
    category: "Language",
  },
  {
    id: Templates.PHP,
    name: "PHP",
    description: "Server-side scripting Language",
    icon: "/php.svg",
    color: "#777BB4",
    popularity: 4,
    tags: ["Backend"],
    features: ["Laravel", "Web"],
    category: "Backend",
  },
  {
    id: Templates.RUBY,
    name: "Ruby",
    description: "Developer-friendly Language",
    icon: "/ruby.svg",
    color: "#CC342D",
    popularity: 3,
    tags: ["Language"],
    features: ["Rails", "Convention"],
    category: "Language",
  },

  // DEV / RUNTIME
  {
    id: Templates.DOCKER_NODE,
    name: "Docker (Node)",
    description: "Containerized Node.js app",
    icon: "/docker.svg",
    color: "#2496ED",
    popularity: 4,
    tags: ["DevOps"],
    features: ["Containers", "Isolation"],
    category: "Backend",
  },
  {
    id: Templates.TYPESCRIPT_NODE,
    name: "Node + TypeScript",
    description: "Typed Node Backend",
    icon: "/typescript.svg",
    color: "#3178C6",
    popularity: 5,
    tags: ["Backend"],
    features: ["Type Safety", "Scalable"],
    category: "Backend",
  },
  {
    id: Templates.DOCKER_PYTHON,
    name: "Docker (Python)",
    description: "Containerized Python application",
    icon: "/docker.svg",
    color: "#2496ED",
    popularity: 4,
    tags: ["DevOps"],
    features: ["Containers", "Isolation"],
    category: "Backend",
  },
  {
    id: Templates.BUN_APP,
    name: "Bun App",
    description: "Fast JavaScript & TypeScript runtime",
    icon: "/Bun.svg",
    color: "#FBF0DF",
    popularity: 4,
    tags: ["JavaScript", "Runtime"],
    features: ["Fast Startup", "Built-in Tooling"],
    category: "Backend",
  },
  {
    id: Templates.DENO_APP,
    name: "Deno App",
    description: "Secure modern JavaScript runtime",
    icon: "/deno.svg",
    color: "000000",
    popularity: 4,
    tags: ["JavaScript", "TypeScript"],
    features: ["Secure by Default", "Native TypeScript"],
    category: "Backend",
  },
];